services:
  valkey:
    image: valkey/valkey:8-alpine
    tmpfs:
      - /data:size=256M,mode=0755
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  image-receiver:
    depends_on:
      valkey:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/image-receiver/Dockerfile
    tmpfs:
      - /data:size=256M,mode=0755
    labels:
      - traefik.enable=true
      - traefik.http.routers.image-receiver.rule=PathPrefix(`/receiver`)
      - traefik.http.services.image-receiver.loadbalancer.server.port=3000
      - traefik.http.middlewares.image-receiver-strip.stripprefix.prefixes=/receiver
      - traefik.http.routers.image-receiver.middlewares=image-receiver-strip

  image-processor:
    depends_on:
      valkey:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/image-processor/Dockerfile
    tmpfs:
      - /data:size=256M,mode=0755
    deploy:
      replicas: 3
    labels:
      - traefik.enable=true
      - traefik.http.routers.image-processor.rule=PathPrefix(`/processor`)
      - traefik.http.services.image-processor.loadbalancer.server.port=3000
      - traefik.http.middlewares.image-processor-strip.stripprefix.prefixes=/processor
      - traefik.http.routers.image-processor.middlewares=image-processor-strip

  traefik:
    image: traefik:3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 3000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: shiki-network
