services:
  image-processor:
    build:
      context: .
      dockerfile: docker/go/Dockerfile.service
      args:
        SERVICE_DIR: services/image-processor
        LIBRARY_DIR: libs/go

networks:
  default:
    name: shiki-network
