services:
  valkey:
    image: valkey/valkey:8-alpine
    tmpfs:
      - /data:size=256M,mode=0755
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  receiver:
    depends_on:
      valkey:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/receiver/Dockerfile
    volumes:
      - ./data/receiver:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.receiver.rule=PathPrefix(`/receiver`)
      - traefik.http.services.receiver.loadbalancer.server.port=3000
      - traefik.http.middlewares.receiver-strip.stripprefix.prefixes=/receiver
      - traefik.http.routers.receiver.middlewares=receiver-strip

  processor:
    depends_on:
      valkey:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/processor/Dockerfile
    volumes:
      - ./data/processor:/data
    deploy:
      replicas: 3
    labels:
      - traefik.enable=true
      - traefik.http.routers.processor.rule=PathPrefix(`/processor`)
      - traefik.http.services.processor.loadbalancer.server.port=3000
      - traefik.http.middlewares.processor-strip.stripprefix.prefixes=/processor
      - traefik.http.routers.processor.middlewares=processor-strip

  metadata:
    depends_on:
      valkey:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/metadata/Dockerfile
    volumes:
      - ./data/metadata:/data

  storage:
    depends_on:
      valkey:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/storage/Dockerfile
    volumes:
      - ./data/storage:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.storage.rule=PathPrefix(`/storage`)
      - traefik.http.services.storage.loadbalancer.server.port=3000
      - traefik.http.middlewares.storage-strip.stripprefix.prefixes=/storage
      - traefik.http.routers.storage.middlewares=storage-strip

  traefik:
    image: traefik:3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 3000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: shiki-network
